services:
  sma200-backend:
    container_name: "sma200-backend"
    build: .
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - services-net
    volumes:
      - ./config/msmtprc:/etc/msmtprc:ro
      - sma200-data:/app/data
    restart: unless-stopped

networks:
  services-net:
    external: true

volumes:
  sma200-data: