[project]
name = "200sma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.121.0",
    "gunicorn>=23.0.0",
    "ipykernel>=7.1.0",
    "pandas-market-calendars>=5.1.3",
    "yfinance>=0.2.66",
]
